ALTER TABLE documents
    ADD COLUMN title VARCHAR(255) NOT NULL DEFAULT 'Untitled document',
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;



